
name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

concurrency: ci-${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Static Analysis
        uses: pre-commit/action@v3.0.0

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest tests/ -s -v

  synth-test-1kd-dev:
    needs: tests
    uses: "./.github/workflows/synth-test.yml"
    with:
      CONTEXT: 1kd-dev

  synth-test-pec-dev:
    needs: tests
    uses: "./.github/workflows/synth-test.yml"
    with:
      CONTEXT: pec-dev

  synth-test-amp-ad-dev:
    needs: tests
    uses: "./.github/workflows/synth-test.yml"
    with:
      CONTEXT: amp-ad-dev

  synth-test-1kd-prod:
    needs: tests
    uses: "./.github/workflows/synth-test.yml"
    with:
      CONTEXT: 1kd-prod

  synth-test-pec-prod:
    needs: tests
    uses: "./.github/workflows/synth-test.yml"
    with:
      CONTEXT: pec-prod

  synth-test-amp-ad-prod:
    needs: tests
    uses: "./.github/workflows/synth-test.yml"
    with:
      CONTEXT: amp-ad-prod

  cdk-deploy-dev:
    if: ${{github.ref == 'refs/heads/dev'}}
    needs: [tests, synth-test-1kd-dev, synth-test-pec-dev, synth-test-amp-ad-dev]
    uses: "./.github/workflows/aws-deploy.yml"
    secrets: inherit
    with:
      CONTEXT_1KD: 1kd-dev
      CONTEXT_PEC: pec-dev
      CONTEXT_AMP: amp-ad-dev
      ROLE_TO_ASSUME: arn:aws:iam::634210816736:role/sagebase-github-oidc-sage-ProviderRole

  cdk-deploy-prod:
    if: ${{github.ref == 'refs/heads/prod'}}
    needs: [tests, synth-test-1kd-prod, synth-test-pec-prod, synth-test-amp-ad-prod]
    uses: "./.github/workflows/aws-deploy.yml"
    secrets: inherit
    with:
      CONTEXT_1KD: 1kd-prod
      CONTEXT_PEC: pec-prod
      CONTEXT_AMP: amp-ad-prod
      ROLE_TO_ASSUME: arn:aws:iam::593604776210:role/sagebase-github-oidc-sage-ProviderRole
